[keys.insert]
j = { k = "normal_mode"}

[keys.normal."space"]
o = "file_picker_in_current_buffer_directory"

[editor]
cursorline = true
lsp.display-inlay-hints = true

[editor.inline-diagnostics]
cursor-line = "hint"

[keys.normal]
D = ["ensure_selections_forward", "extend_to_line_end", "delete_selection"]

[editor.file-picker]
hidden = false


